import nameBacks from "./texts_cocukhaklari.json";

export const FilterTabs = Object.keys(nameBacks).map((key, index) => {
  // Create an array of constants
  const images = [
    require("../../img/cocuk_haklari_cards/c1.png"),
    require("../../img/cocuk_haklari_cards/c2.png"),
    require("../../img/cocuk_haklari_cards/c3.png"),
    require("../../img/cocuk_haklari_cards/c4.png"),
    require("../../img/cocuk_haklari_cards/c5.png"),
    require("../../img/cocuk_haklari_cards/c6.png"),
    require("../../img/cocuk_haklari_cards/c7.png"),
    require("../../img/cocuk_haklari_cards/c8.png"),
    require("../../img/cocuk_haklari_cards/c9.png"),
    require("../../img/cocuk_haklari_cards/c10.png"),
    require("../../img/cocuk_haklari_cards/c11.png"),
    require("../../img/cocuk_haklari_cards/c12.png"),
    require("../../img/cocuk_haklari_cards/c13.png"),
    require("../../img/cocuk_haklari_cards/c14.png"),
    require("../../img/cocuk_haklari_cards/c15.png"),
    require("../../img/cocuk_haklari_cards/c16.png"),
    require("../../img/cocuk_haklari_cards/c17.png"),
    require("../../img/cocuk_haklari_cards/c18.png"),
    require("../../img/cocuk_haklari_cards/c19.png"),
    require("../../img/cocuk_haklari_cards/c20.png"),
    require("../../img/cocuk_haklari_cards/c21.png"),
    require("../../img/cocuk_haklari_cards/c22.png"),
    require("../../img/cocuk_haklari_cards/c23.png"),
    require("../../img/cocuk_haklari_cards/c24.png"),
    require("../../img/cocuk_haklari_cards/c25.png"),
    require("../../img/cocuk_haklari_cards/c26.png"),
    require("../../img/cocuk_haklari_cards/c27.png"),
    require("../../img/cocuk_haklari_cards/c28.png"),
    require("../../img/cocuk_haklari_cards/c29.png"),
    require("../../img/cocuk_haklari_cards/c30.png"),
    require("../../img/cocuk_haklari_cards/c31.png"),
    require("../../img/cocuk_haklari_cards/c32.png"),
    require("../../img/cocuk_haklari_cards/c33.png"),
    require("../../img/cocuk_haklari_cards/c34.png"),
    require("../../img/cocuk_haklari_cards/c35.png"),
    require("../../img/cocuk_haklari_cards/c36.png"),
    require("../../img/cocuk_haklari_cards/c37.png"),
    require("../../img/cocuk_haklari_cards/c38.png"),
    require("../../img/cocuk_haklari_cards/c39.png"),
    require("../../img/cocuk_haklari_cards/c40.png"),
    require("../../img/cocuk_haklari_cards/c41.png"),
    require("../../img/cocuk_haklari_cards/c42.png"),
  ];

  return {
    nameFront: `c${index + 1}`,
    nameBack: nameBacks[key],
    icon: images[index],
  };
});
